---

- name: install s3cmd for uploading nginx logs
  apt: >
    name=s3cmd
    state=present

- name: creating nginx ssl cert repo directory
  file: >
    path=/etc/ssl/nginx
    state=directory
    group=root
    mode=0700

- name: adding nginx signing key
  apt_key: >
    data="{{ lookup('file', 'nginx_signing.key') }}"
    state=present

- name: downloading apt-get nginx repository
  copy: >
    src=90nginx
    dest=/etc/apt/apt.conf.d/90nginx
    mode=0700

- name: find Ubuntu release
  shell: lsb_release -cs
  register: release

- name: adding sources.list deb-src url for nginx
  lineinfile: >
    line="deb https://nginx.org/packages/mainline/ubuntu/ {{ release.stdout }} nginx"
    dest=/etc/apt/sources.list.d/nginx.list
    state=present
    create=yes
    group=root
    mode=0700

- name: installing nginx via apt-get
  apt: >
    pkg=nginx
    state=latest
    update_cache=yes

- name: install dhparam file
  copy: >
   src=dh-2048.pem
   dest=/etc/ssl/nginx/dhparam.pem
   owner=www-data
   group=adm
   mode=0600

- name: remove default nginx conf
  file: >
    path=/etc/nginx/conf.d/default.conf
    state=absent

- name: remove default ssl nginx conf
  file: >
    path=/etc/nginx/conf.d/example_ssl.conf
    state=absent

- name: install main nginx configuration files
  copy: >
    src={{ item.name }}
    dest={{ item.path }}{{ item.name }}
    owner=www-data
    group=root
    mode=0644
  with_items:
    - { name: nginx.conf, path: /etc/nginx/ }
