---

- name: install motd
  template: >
    src=motd.j2
    dest=/etc/motd
    mode=644

- name: set system timezone to UTC
  file: >
    src=/usr/share/zoneinfo/UTC
    dest=/etc/localtime
    state=link
    owner=root
    group=root
    force=yes

# Locale fixes for Ubuntu
- name: install EN language pack
  apt: >
    name=language-pack-en-base
    state=latest

- name: regenerate en_US locale
  shell: locale-gen en_US en_US.UTF-8

- name: reconfigure locales
  shell: dpkg-reconfigure locales

- name: install jq 1.5
  get_url: >
    url=https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
    dest=/usr/bin/jq
    mode=0555
    force=yes
